#+TITLE:README
#+AUTHOR: Karim Aziiev
#+EMAIL: karim.aziiev@gmail.com

* md-edit-org

Edit Markdown In Org Mode.

** Requirements

+ Emacs >= 27.1
+ pandoc

** Installation

*** Manual

Download the source code and put it wherever you like and add the directory to the load path:

#+begin_src elisp :eval no

(add-to-list 'load-path "/path/to/md-edit-org)

(require 'md-edit-org)

#+end_src

*** With use-package and straight

#+begin_src elisp :eval no

(use-package md-edit-org
	:straight (md-edit-org
			       :repo "KarimAziev/md-edit-org"
			       :type git
			       :host github)
	:bind ((:map md-edit-org-edit-mode-map
			         ([remap save-buffer] . md-edit-org-save)
			         ("C-c C-c" . md-edit-org-done)
			         ("C-c C-k" . md-edit-org-discard)
			         ("C-c '" . md-edit-org-done)))
	:commands (md-edit-org-edit-markdown-in-org))

#+end_src

** Usage
Run in markdown buffer:

~M-x md-edit-org-edit-markdown-in-org RET~.

A new buffer is created with original content, converted to org, and the buffer is switched into an ~org-mode~.

When done, exit with =C-c C-c= (command ~md-edit-org-done~).

The edited text will then converted to markdown and replace the area in the original markdown buffer. To exit without changes - =C-c C-k= (command ~md-edit-org-discard~).

Default bindings:
| Key                   | Command             | 
|-----------------------+---------------------|
| <remap> <save-buffer> | md-edit-org-save    |
| C-c C-c               | md-edit-org-done    |
| C-c C-k               | md-edit-org-discard |
| C-c '                 | md-edit-org-done    |

You can change them by modifing ~md-edit-org-edit-mode-map~.

** Customization

*** ~md-edit-org-persistent-message~
Non-nil means show persistent exit help message while editing src examples. The message is shown in the header-line, which will be created in the first line of the window showing the editing buffer.
*** ~md-edit-org-pandoc-executable~
The path to the pandoc executable.
*** ~md-edit-org-pandoc-output-type~
Markdown output type for ~pandoc.~
